### PR TITLE
download picture of a size that fits the request

### PR DESCRIPTION
**Pull request by mathieudutour**
instead of downloading pictures of 1080p, we will ask for pictures of the size we want. 
Should provide a nice performance boost for small pictures

### CODE REVIEW

**Comment by bomberstudios** [comment]
I like this, but I think we should request images that are at least 2x (or even 3x) larger than the frame because chances are they’ll be exported as Retina assets.

**Comment by mathieudutour** [comment]
Ah I didn't think about that. There is a `dpi` parameter we can set (to `2` or `3` up to `8`) to control the pixel density.

But do you think they will use random data as assets?

**Comment by mathieudutour** [comment]
The ideal solution would be a setting

**Comment by bomberstudios** [comment]
Let’s go for `2` as dpi, just to make sure the image doesn’t look like shit on Retina screens. If the images need to be used as assets, one can always visit the source page at Unsplash and download the original file.

**Pull request merged**
